# Generated by Django 3.0.3 on 2020-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_regis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
